<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Mobile part of the robot -->

    <!-- For intertia: https://en.wikipedia.org/wiki/List_of_moments_of_inertia -->

    <!-- =============== -->
    <!-- Xacro variables -->
    <!-- =============== -->
    <xacro:property name="base_lenght" value="0.7"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>

    <xacro:property name="weel_radius" value="0.1"/>
    <xacro:property name="weel_length" value="0.05"/>
    
    <xacro:property name="caster_radius" value="${weel_radius / 2.0}"/>

    <!-- Macro for the side wheels -->
    <xacro:macro name="weel_macro" params="dy w_name">
        <link name="${w_name}">
            <visual>
                <geometry>
                    <cylinder radius="${weel_radius}" length="${weel_length}"/>
                </geometry>
                <origin xyz="0.0 ${dy} 0.0" rpy="${pi/2.0} 0.0 0.0"/>
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${weel_radius}"/>
                </geometry>
                <origin xyz="0.0 ${dy} 0.0" rpy="${pi/2.0} 0.0 0.0"/>
            </collision>
            <xacro:solid_cilinder_intertia m="${60.0 * weel_radius *weel_length}" r="${weel_radius}" 
                    h="${weel_length}" o_xyz="0.0 ${dy} 0.0" o_rpy="${pi/2.0} 0.0 0.0" />
        </link>
    </xacro:macro>


    <!-- ============================= -->
    <!-- <<<< Rigid parts (links) >>>> -->
    <!-- ============================= -->
    
    <!-- Base link-->
    <link name="body_link">
        <visual>
            <geometry>
                <!-- Medidas em metros -->
                <box size="${base_lenght} ${base_width} ${base_height}"/> 
            </geometry>
            <!-- rpy = roll, pitch, yaw-->
            <origin xyz="0.0 0.0 ${base_height / 2.0}" rpy="0.0 0.0 0.0"/>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_lenght} ${base_width} ${base_height}"/> 
            </geometry>
            <origin xyz="0.0 0.0 ${base_height / 2.0}" rpy="0.0 0.0 0.0"/>
        </collision>

        <xacro:box_intertia m="5.0" x="${base_lenght}" y="${base_width}" z="${base_height}"
                            o_xyz="0.0 0.0 ${base_height / 2.0}" o_rpy="0.0 0.0 0.0"/>
    </link>

    <link name="second_link">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.2"/>
            </geometry>
            <origin xyz="0.0 0.0 0.1" rpy="0.0 0.0 0.0"/>
            <material name="grey"/>
        </visual>   
        <collision>
            <geometry>
                <cylinder radius="0.1" length="0.2"/>
            </geometry>
            <origin xyz="0.0 0.0 0.1" rpy="0.0 0.0 0.0"/>
        </collision>

        <xacro:solid_cilinder_intertia m="3.0" r="0.1" h="0.2"
                                       o_xyz="0.0 0.0 0.1" o_rpy="0.0 0.0 0.0" />
    </link>

    <link name="visor_link">
        <visual>
            <geometry>parent_link
                <box size="0.05 0.05 0.05"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:box_intertia m="0.3" x="0.05" y="0.05" z="0.05"
                            o_xyz="0.0 0.0 0.0" o_rpy="0.0 0.0 0.0"/>
    </link>

    <xacro:weel_macro dy="${-weel_length / 2.0}" w_name="right_weel_link"/>
    <xacro:weel_macro dy="${weel_length / 2.0}" w_name="left_weel_link"/>

    <link name="center_weel_link">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${-caster_radius}" rpy="0.0 0.0 0.0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${-caster_radius}" rpy="0.0 0.0 0.0"/>
            <material name="grey"/>
        </collision>
        <xacro:solid_sphere_intertia m="${caster_radius * 4}" r="${caster_radius}"
                             o_xyz="0.0 0.0 ${-caster_radius}" o_rpy="0.0 0.0 0.0"/>
    </link>

    <!-- Base Link-->
    <link name="base_link">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>   
    </link>


    <!-- ================ -->
    <!-- <<<< Joints >>>> -->
    <!-- ================ -->
    <joint name="base_body_joint" type="fixed">
        <parent link="base_link"/>
        <child link="body_link"/>
        <origin xyz="0.0 0.0 ${weel_radius}" rpy="0.0 0.0 0.0"/>
    </joint>

    <joint name="body_second_joint" type="revolute">
        <parent link="body_link"/>
        <child link="second_link"/>
        <origin xyz="0.0 0.0 ${base_height}" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="-1.0" upper="1.0" effort="0.2" velocity="0.2"/>
    </joint>

    <joint name="joint_name" type="fixed">
        <parent link="second_link"/>
        <child link="visor_link"/>
        <origin xyz="0.1 0.0 0.2" rpy="0.0 0.0 0.0"/>
    </joint>

    <joint name="left_weel_body" type="continuous">
        <parent link="body_link"/>
        <child link="left_weel_link"/>
        <origin xyz="${-base_lenght / 4.0} ${base_width / 2.0} 0.0" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <joint name="right_weel_body" type="continuous">
        <parent link="body_link"/>
        <child link="right_weel_link"/>
        <origin xyz="${-base_lenght / 4.0} ${-base_width / 2.0} 0.0" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <joint name="center_weel_body" type="fixed">
        <parent link="body_link"/>
        <child link="center_weel_link"/>
        <origin xyz="${base_lenght / 3.0} 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>
</robot>